#!/bin/bash -l
#SBATCH -N 1
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -n 2
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH --time=1-23:00:00
#SBATCH --mem 300G

#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet_10.json'
#
#############
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_10.json'
#
#
###############
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet_10.json'
#
#
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt_10.json'
#python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr_10.json'
#python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn_10.json'
#python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet_10.json'

##################
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet_5.json'

############

python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_5.json'


##############
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet_5.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt_5.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr_5.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn_5.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_5.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet_5.json'


#############
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet_15.json'

############

python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_15.json'


##############
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet_15.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt_15.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr_15.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn_15.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_15.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet_15.json'


##############
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet_20.json'

############

python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_20.json'


##############
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet_20.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt_20.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr_20.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn_20.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet_20.json'

