python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_10.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_10.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_10.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_10.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_10.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_10.json'


python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_10.json'
python largeFileTest.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_10.json'
python largeFileTest_DNN.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_10.json'
python largeFileTest_TabNet.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_10.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_10.json'
