
#############
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/EURLEX57K_MiniLM-L6-v2-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/FakeNews_MiniLM-L6-v2-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr.model' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn.h5' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-MiniLM-L6-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet.pth.zip' --path_save_res './result/all-MiniLM-L6-v2/CancerDoc_MiniLM-L6-v2-tabnet_20.pfd.json'

############

python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/EURLEX57K_distilroberta-v1-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/FakeNews_distilroberta-v1-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr.model' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn.h5' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-distilroberta-v1/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-distilroberta-v1/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet.pth.zip' --path_save_res './result/all-distilroberta-v1/CancerDoc_distilroberta-v1-tabnet_20.pfd.json'


##############
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/EURLEX57K_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/EURLEX57K_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/EURLEX57K_mpnet-base-v2-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/FakeNews_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/FakeNews_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/FakeNews_mpnet-base-v2-tabnet_20.pfd.json'


python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-rf_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dt_20.pfd.json'
python largeFileTest_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr.model' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-lr_20.pfd.json'
python largeFileTest_DNN_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn.h5' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-dnn_20.pfd.json'
python largeFileTest_TabNet_pfd.py --path_file_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_X.pkl' --path_file_y './data/embedding_data/all-mpnet-base-v2/CancerDoc_file_y.pkl' --path_chunk_embedding_X './data/embedding_data/all-mpnet-base-v2/CancerDoc_chunk_X_20.pkl' --path_target_model './target_models/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet.pth.zip' --path_save_res './result/all-mpnet-base-v2/CancerDoc_mpnet-base-v2-tabnet_20.pfd.json'
